version: '2'
services:
    proxy:
        image: skilgarriff/alpine-caddy
        ports:
            -   "80:80"
            -   "443:443"
        volumes:
            -   ./compose/proxy/Caddyfile:/etc/Caddyfile
            -   ./.caddy:/root/.caddy
        networks:
            - frontend

    seankilgarriff.com:
        expose:
            -   80
